import { useEffect, useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import Header from '../components/Header.jsx'
import StarMap from '../components/StarMap.jsx'
import ElementChart from '../components/ElementChart.jsx'
import ProfileCard from '../components/ProfileCard.jsx'
import TraitProfile from '../components/TraitProfile.jsx'
import SpectralBar from '../components/SpectralBar.jsx'
import Loader from '../components/Loader.jsx'
import ErrorBox from '../components/ErrorBox.jsx'
import { postPart2 } from '../api/client.js'

export default function Profile() {
  const { state } = useLocation()
  const navigate = useNavigate()
  const part1 = state?.part1
  const birth = state?.birth

  const [part2, setPart2] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)

  useEffect(() => {
    if (!part1) return
    let cancelled = false
    setLoading(true)
    setError(null)
    postPart2(part1)
      .then((data) => {
        if (!cancelled) setPart2(data)
      })
      .catch((err) => {
        if (!cancelled) setError(err.message)
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => {
      cancelled = true
    }
  }, [part1])

  if (!part1) {
    return (
      <div className="page profile-page">
        <Header />
        <main className="empty-state">
          <h1>No profile yet.</h1>
          <p>Enter your birth details on the home page to generate a Stellar DNA profile.</p>
          <Link to="/" className="btn btn-primary">Go to home</Link>
        </main>
      </div>
    )
  }

  return (
    <div className="page profile-page">
      <Header />
      <main className="profile-main">
        <section className="profile-header">
          <div>
            <p className="hero-eyebrow">Your Stellar DNA</p>
            <h1 className="profile-title">
              {birth?.location_name || 'Your birth sky'}
            </h1>
            <p className="profile-sub">
              {birth?.birth_date} · {birth?.birth_time}
            </p>
          </div>
          <div className="profile-actions">
            <button className="btn btn-ghost" onClick={() => navigate('/')}>
              ← New profile
            </button>
          </div>
        </section>

        <section className="map-section">
          <StarMap stars={part1.star_positions || []} />
        </section>

        <section className="card-section">
          <ProfileCard data={part1} birth={birth} />
        </section>

        <section className="two-col">
          <div className="card chart-card">
            <h2 className="card-title">Elemental composition</h2>
            <p className="card-sub">
              Fractional mass of each element in your body, traced to the stellar process that forged it.
            </p>
            <ElementChart data={part1.element_percentages || {}} />
          </div>
          <div className="card spectral-card">
            <SpectralBar weights={part1.spectral_weights || {}} />
          </div>
        </section>

        <section className="card-section">
          {loading && <Loader label="Computing your trait profile…" />}
          {error && <ErrorBox message={error} onRetry={() => setError(null)} />}
          {part2 && <TraitProfile data={part2} />}
        </section>

        <section className="disclaimer">
          <p>
            Note: Stellar DNA is a poetic interpretation inspired by real stellar physics,
            not a scientific prediction. The 5 trait scores are reproducible math derived
            from the birth sky; the narrative is generated by an LLM and is unique to your input.
          </p>
        </section>
      </main>
    </div>
  )
}
